### ISSUE TITLE
IITCm Android 10 always instant crash at startup

### ISSUE THREAD

**Issue by 1valdis** [IITC-CE/ingress-intel-total-conversion#295]
IITC mobile latest version from Google Play store.
Samsung S10e, Android 10.
The app crashes each time I start it. One second of white screen and then crash. Even logo and menu doesn't appear. I've sent tens of crash reports already via "App keeps stopping" screen but can provide more data if needed. Please fix ASAP since it's going to be painful to live without IITC during the upcoming global event..

**Comment by MysticJay** [comment]
https://t.me/iitc_group/6121

**Comment by modos189** [comment]
Ok, I see crash report

**Comment by johnd0e** [comment]
![263836866_453991](https://user-images.githubusercontent.com/1838643/71182537-e9aeeb80-227e-11ea-8202-4b319ba37dc1.jpg)

https://github.com/IITC-CE/ingress-intel-total-conversion/blob/4e0f388d9cdeb50519f356a5d90807006f43f9c8/mobile/app/src/main/java/org/exarhteam/iitc_mobile/IITC_WebChromeClient.java#L174

https://github.com/IITC-CE/ingress-intel-total-conversion/blob/4e0f388d9cdeb50519f356a5d90807006f43f9c8/mobile/app/src/main/java/org/exarhteam/iitc_mobile/IITC_Mobile.java#L812-L817

**Comment by modos189** [comment]
This error is not only in android 10. I've seen the same reports since android 8. Most of reports are from Samsung phones, but there are other manufacturers as well.

I can get rid of application crash by simply adding a check, but it is better to find the root of the problem.

**Comment by 1valdis** [comment]
Updating Android 10 from Security patch level 1 December 2019 to Security patch level 1 January 2020 fixed the crash. Actually it fixed many more crashes in Google Maps, Gmail, Google Street View and Ingress (when tapping Nominations button). Seems like initial Samsung Android 10 release has messed something up and with January update everything was fixed.

**Comment by modos189** [comment]
Unfortunately, similar crashes are found in other versions of android. Let issue remain open for now.

**Comment by johnd0e** [comment]
Perhaps it's time to close this issue.
