### ISSUE TITLE
Unable to share portal

### ISSUE THREAD

**Issue by soerenkk** [IITC-CE/ingress-intel-total-conversion#391]
I've discovered that I'm not able to share some portals, while others work just fine.

I've found a couple and developed a theory since I found a thing they had in common. The ones that don't work contain the special letter "å" or "Å" (in caps). The letter is used in the Danish language, others are "æ/Æ" and "ø/Ø", however those work just fine. 

When I try to share the portal location, using the normal button from the portal info screen, nothing happens. I can see iitc register me clicking on the button, and normally there would open a menu on how or where to I would share that portal. Well with these, nothing happens. I can click the share button again, I've tried to wait and give it a minutes, but nothing. If I go back to the map and click on another portal, try and share that, it works as normal. If I then go back to the first portal again, still nothing.

This is one of those I've found, and containing the special letter which I suspect might be causing the problem, or at least have some influence on the problem:

https://intel.ingress.com/intel?ll=55.3366,10.331674&z=16&pll=55.33672,10.330928

**Comment by SapphicFire** [comment]
@soerenkk I am able to replicate this issue on my device, and noted that a portal just north of the example linked contains 'Å' [here](https://intel.ingress.com/?ll=55.33729329499879,10.331598385837056&z=16) and will call the Share 'drawer' per expected functionality. Will investigate if this highlights the issue as being due to index in portal name (and perform better investigation when at PC)

**Comment by SapphicFire** [comment]
@SapphicFire Further investigation shows that issue can also be encountered on desktop, and that it is caused by the \n newline character in this context. Rectification on desktop could be done by parsing the portal name to strip invalid characters like newlines - this may be the issue with mobile too, still investigating to confirm

**Comment by SapphicFire** [comment]
Investigation has confirmed that the issue present in Desktop is due to lack of escaping for newline characters, and not an encoding issue for characters such as A-ring. The fact this hadn't been escaped is understandable, it would be reasonable to assume Niantic would not permit newlines in portal names.

The issue can be found in utils_misc.js here:
https://github.com/IITC-CE/ingress-intel-total-conversion/blob/3f4867a4a4ab5dd86d093fcaa9829f3267f70e9b/core/code/utils_misc.js#L335-L337

Unfortunately I do not have sufficient experience with mobile development to identify if this is the same issue with the mobile share button, but this seems likely at this point in time.

**Comment by johnd0e** [comment]
> Investigation has confirmed that the issue present in Desktop

I do not have "Share" button in Desktop.
Explain how I can reproduce the issue,

**Comment by johnd0e** [comment]
Both mentioned issues should be fixed, check latest test build.

**Comment by SapphicFire** [comment]
@johnd0e Guessing you found it by later notes, Map Links provides mirrored functionality

**Comment by SapphicFire** [comment]
Resolution confirmed on this issue in latest test build.

**Comment by soerenkk** [comment]
> Resolution confirmed on this issue in latest test build.

Mine is still not working in the "IITC Mobile" neither the "IITC Mobile Test" build?
